PM-1102 created and updated tables
pagopa/pagopa-payment-transactions-gateway pull request #140
Opened 2022-09-28 14:37 UTC by DavideAmatoNexi

#### List of Changes

Created PP_PGS_RESPONSE_INFO table and updated PP_PGS_REQUEST_INFO table.

#### Motivation and Context

This was done in order to make an xpay payment

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.

### Link to story

https://pagopa.atlassian.net/browse/PM-1102

2022-10-03 08:15 UTC, alessandrodossi requested changes

2022-10-04 12:03 UTC, infantesimone commented
@DavideAmatoNexi just a few more unit tests :-)

2022-10-04 12:04 UTC, infantesimone commented on src/main/java/it/pagopa/pm/gateway/entity/PaymentResponseEntity.java
> +    @Column(name = "HTML")
is the `html` returned by `xpay`?

2022-10-04 12:06 UTC, infantesimone commented on src/main/java/it/pagopa/pm/gateway/entity/PaymentRequestEntity.java
> +    @Column(name = "HTML")
why is this data on both tables?

2022-10-04 14:36 UTC, DavideAmatoNexi commented
Close with a comment:
Everything is located on the PM-1100 branch (https://github.com/pagopa/pagopa-payment-transactions-gateway/tree/PM-1100-POST-Request-Payments-xPay)

2022-10-04 14:36 UTC, closed without merging