PM-1215 Added DB scripts for VPOS
pagopa/pagopa-payment-transactions-gateway pull request #174
Opened 2022-11-23 08:34 UTC by DavideAmatoNexi

#### List of Changes

 Added DB scripts for VPOS

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.

### Link to story

https://pagopa.atlassian.net/browse/PM-1215

2022-11-24 15:04 UTC, alessandrodossi requested changes

2022-11-24 15:04 UTC, alessandrodossi commented on devops/db/liquibase/changelogs/payment-transaction-gateway/incremental-changelogs/V7_PM_1215-changelog.xml
> +    <changeSet id="V13__PM_1215_ADD_IS_FIRST_PAYMENT_AND_COLUMN_RESPONSE_TYPE" author="liquibase" failOnError="true" context="incremental">
@DavideAmatoNexi contexts incremental-uat and incremental-prod are needed in this changeset in order to execute the scripts in UAT and production environments
```suggestion
    <changeSet id="V13__PM_1215_ADD_IS_FIRST_PAYMENT_AND_COLUMN_RESPONSE_TYPE" author="liquibase" failOnError="true" context="incremental or incremental-uat or incremental -prod">
```

2022-11-25 10:34 UTC, giovanniberti commented
Can you port these changes also to the postres profile?

2022-12-05 10:42 UTC, giovanniberti approved these changes

2022-12-05 10:52 UTC, alessandrodossi approved these changes

2022-12-05 10:52 UTC, merged